# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PromiseKitExample' do

pod "PromiseKit"
pod "MagicalRecord"

end

target 'PromiseKitExampleTests' do

end

