language: objective-c

xcode_workspace: Json-Api-Example.xcworkspace
xcode_scheme: Staging

before_install:
    - rvm install 2.2.5
    - export LANG=en_US.UTF-8
    - sudo gem install cocoapods -v '0.39.0'

install:
    - pod install

script:
    - ./Json-Api-Example/Scripts/build.sh
    - ./Json-Api-Example/Scripts/test.sh

branches:
    only:
        - master

notifications:
    hipchat:
        rooms:
            - $API_TOKEN@ios-base
    email:
        recipients:
            # - one@example.com
            # - other@example.com
        on_success: change # [always|never|change] # default: change
        on_failure: change # [always|never|change] # default: always
