platform :ios, '8.2'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


abstract_target 'Abstract' do
    pod 'FSHelpers+Swift', :git => 'https://github.com/fs/FSHelper.git'
    
    # Analytics
    pod 'Fabric'
    pod 'Crashlytics'
    
    # Libraries
    pod 'Spine', :git => 'https://github.com/wvteijlingen/Spine.git'
    
    target 'Json-Api-Example' do
    end
    
    target 'Json-Api-ExampleTests' do
    end
    
    target 'Json-Api-ExampleUITests' do
    end
end

# Helpers

#pod 'SDWebImage'
#pod 'NSDate-Extensions'
#pod 'Reachability'
#pod 'SVProgressHUD'
#pod 'SSKeychain'
#pod 'MKStoreKit'
