platform :ios, '8.2'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


abstract_target 'Abstract' do
    pod 'FSHelpers+Swift', :git => 'https://github.com/fs/FSHelper.git'
    
    # Analytics
    pod 'Fabric'
    pod 'Crashlytics'
    
    # Libraries
    pod 'AFNetworking'
    pod 'MagicalRecord'
    
    # Authorization
    pod 'IOSLinkedInAPI', :git => 'https://github.com/jeyben/IOSLinkedInAPI.git', :branch => 'master'
    pod 'Google/SignIn'
    
    # Helpers
    pod 'SVProgressHUD'
    
    target 'Authorization-module' do
    end
    
    target 'Authorization-moduleTests' do
    end
    
    target 'Authorization-moduleUITests' do
    end
    
end

# Helpers

#pod 'SDWebImage'
#pod 'NSDate-Extensions'
#pod 'Reachability'

#pod 'SSKeychain'
#pod 'MKStoreKit'
