platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

# Helpers
pod 'FSHelpers+Swift', :git => 'https://github.com/fs/FSHelper.git', :branch => 'master'
#pod 'NSDate-Extensions'
#pod 'NSData+Base64'

# Analytics
pod 'Fabric'
pod 'Crashlytics'

pod 'Google-Mobile-Ads-SDK', '~> 7.0'

pod 'FBSDKCoreKit', '~> 4.10'
pod 'FBAudienceNetwork', '~> 4.10'

# Libraries
pod 'AFNetworking', '~> 2.6'
#pod 'SDWebImage'
#pod 'NSDate-Extensions'
#pod 'MagicalRecord'
#pod 'Reachability'
#pod 'SVProgressHUD'
#pod 'SSKeychain'
#pod 'MKStoreKit'
